# Generated by Django 4.1.13 on 2024-02-01 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'ClassTime',
                'verbose_name_plural': 'ClassTimes',
            },
        ),
        migrations.CreateModel(
            name='Possibilitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='rakhtkan', max_length=200)),
                ('possibilitie', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Possibilitie',
                'verbose_name_plural': 'Possibilities',
            },
        ),
        migrations.CreateModel(
            name='SportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='bascketball', max_length=200)),
                ('sportfield', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SportField',
                'verbose_name_plural': 'SportFields',
            },
        ),
        migrations.CreateModel(
            name='StudiumSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('rate', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('number_people_rate', models.IntegerField(default=0)),
                ('sum_rate', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('discount', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, choices=[('گزینه 1', 'تهران'), ('گزینه 2', 'اصفهان'), ('گزینه 3', 'شیراز')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, choices=[('گزینه 1', 'تهران'), ('گزینه 2', 'اصفهان'), ('گزینه 3', 'شیراز')], max_length=20, null=True)),
                ('area', models.CharField(blank=True, choices=[('گزینه 1', 'تهران'), ('گزینه 2', 'اصفهان'), ('گزینه 3', 'شیراز')], max_length=20, null=True)),
                ('possibilitie_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stadium.possibilitie')),
                ('sportfield_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stadium.sportfield')),
            ],
            options={
                'verbose_name': 'StudiumSet',
                'verbose_name_plural': 'StudiumSets',
            },
        ),
        migrations.CreateModel(
            name='WeeklyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('price', models.CharField(blank=True, max_length=200, null=True)),
                ('booking', models.BooleanField(default=False, verbose_name='در حال رزرو')),
                ('booklable', models.BooleanField(default=False, verbose_name='قابل رزرو')),
                ('reserved', models.BooleanField(default=False, verbose_name='رزرو شده')),
                ('class_time_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.classtime')),
                ('studiumset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.studiumset')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WeeklyReservation',
                'verbose_name_plural': 'WeeklyReservations',
            },
        ),
    ]
