# Generated by Django 4.1.13 on 2024-02-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiumset',
            name='area',
            field=models.CharField(blank=True, choices=[('تهران ', 'تهران'), ('اصفهان ', 'اصفهان'), ('شیراز ', 'شیراز')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studiumset',
            name='city',
            field=models.CharField(blank=True, choices=[('تهران ', 'تهران'), ('اصفهان ', 'اصفهان'), ('شیراز ', 'شیراز')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studiumset',
            name='state',
            field=models.CharField(blank=True, choices=[('تهران ', 'تهران'), ('اصفهان ', 'اصفهان'), ('شیراز ', 'شیراز')], max_length=20, null=True),
        ),
    ]
