# Generated by Django 4.1.13 on 2024-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_alter_studiumset_area_alter_studiumset_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiumset',
            name='area',
            field=models.CharField(blank=True, choices=[('تهران', 'تهران'), ('اصفهان', 'اصفهان'), ('شیراز', 'شیراز')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studiumset',
            name='city',
            field=models.CharField(blank=True, choices=[('تهران', 'تهران'), ('اصفهان ', 'اصفهان'), ('شیراز', 'شیراز')], max_length=20, null=True),
        ),
    ]
