# Generated by Django 4.1.13 on 2024-02-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0004_alter_studiumset_city_alter_studiumset_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiumset',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='studium_images/'),
        ),
    ]
