# Generated by Django 4.1.13 on 2024-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0005_studiumset_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='studiumset',
            name='picture',
        ),
    ]
