# Generated by Django 4.1.13 on 2024-02-02 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0006_photo_remove_studiumset_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiumset',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium.photo'),
        ),
    ]
